.PHONY: clean All

All:
	@echo "----------Building project:[ lab6 - Debug ]----------"
	@cd "lab6" && "$(MAKE)" -f  "lab6.mk"
clean:
	@echo "----------Cleaning project:[ lab6 - Debug ]----------"
	@cd "lab6" && "$(MAKE)" -f  "lab6.mk" clean
